### ISSUE TITLE
Consider providing a non-headless JRE version of tomcat

### ISSUE THREAD

**Issue by weltan** [Azure-App-Service/tomcat#5]
The Tomcat 9 image is based on [tomcat:9-jre8-alpine](https://github.com/docker-library/tomcat/blob/8fffa7246aacceb0e7390aafe978efeea9c104e3/9.0/jre8-alpine/Dockerfile) which uses a headless JRE.

I’ve run into a problem with, for example, generating PDFs and SVGs, that use java.awt.Font, which does not work well in headless mode. Root issue can be seen here: https://github.com/docker-library/openjdk/issues/73.

This type of functionality (generating PDFs) would seem quite common for App Service enterprise Java apps. 

Would it be possible to provide a non-headless tomcat image like [tomcat:9-jre8](https://github.com/docker-library/tomcat/blob/cde74d619bfe2e522d31b02969822b0d0df0bc6c/9.0/jre8/Dockerfile) without alpine, similar to what you have for 8.5? I've already asked upstream Alpine OpenJDK to add the few packages needed for `java.awt.Font` to work, and was rejected (makes sense).

Another option if you want to keep only Alpine because it's a lightweight container option, is to allow the user to select from a pre-defined set of custom tomcat container versions in Azure.

Of course, we can always use our own custom containers, but I think users might prefer to use these Azure-managed containers rather than having to resort to a custom Docker container.

**Comment by jvano** [comment]
The tomcat built-in images for App Service Linux are still in preview and we will make changes but your input is very valuable. Thanks @weltan for the suggestion.

**Comment by weltan** [comment]
Great, thanks for your consideration.

Just so you know, we ended up using your tomcat9 alpine built-in, and installed `fontconfig` and `ttf-dejavu` at run-time using a code-invoked shell command. It ain’t pretty, but it allowed us to stay on the built-in tomcat image.

**Comment by weltan** [comment]
@ernani: I think you might be misunderstanding? We're trying to avoid headless mode, not enable it.

**Comment by ernani** [comment]
@weltan I thought it was the opposite case, in that sense you are right, perhaps you may want to go building a custom docker image and deploy it using Web Apps for containers instead?

**Comment by weltan** [comment]
Yes - creating a custom image would solve this problem. However, as I pointed out in my original post above, it's a huge boon to be able to use the azure-managed containers. Furthermore, it seems like the particular issue my team ran into is a relatively common subclass of "cases where using headless JRE isn't possible" and therefore might be suitable for a more general solution provided by Azure.

That's why I asked about whether they'd consider adding a non-headless managed container.

**Comment by ernani** [comment]
I am a CSA @ Microsoft. I will try to point it out internally your
situation to the Product Group. I will get back to you with an answer ASAP.

Best Regards

Em Sex, 6 de jul de 2018 4:37 PM, Ken Kantzer <notifications@github.com>
escreveu:

**Comment by weltan** [comment]
curious, @ernani, if you've heard anything?

**Comment by ernani** [comment]
I have had the chance to talk to some of the guys internally and some new content are coming in but still with no ETA.

Perhaps @jvano you could also help reinforce this requirement as well.

Best Regards!

**Comment by weltan** [comment]
@jvano @ernani sounds good, totally understand that this is in preview - that’s actually why I reached out, I figured this is the time where changes are still happening regularly!

**Comment by shrishrirang** [comment]
@weltan: https://github.com/Azure-App-Service/tomcat/pull/8 contains changes for building Tomcat 8.5 and 9.0 images using the Ubuntu 18.04 image as the base. The PR is merged and we will be updating the official Azure App Service images (for Tomcat 8.5 and 9.0 both) in Docker Hub this week.

**Comment by shrishrirang** [comment]
We recently changed the base image of the Dockerfiles. However, we aren't using headless jre anymore, so I believe your issue is addressed. But to be sure I would like to test it once. @weltan : Do you have a simple repro app or set of steps I can use to confirm?

**Comment by weltan** [comment]
@shrishrirang hi thanks for this fix. We can confirm that using the new Ubuntu base image in our App service allowed us to remove the workaround, and everything seems to be working.

As for a minimal repro for you to test, I believe any use of `java.awt.Font` should produce an exception in Alpine-headless, but not in Ubuntu, so this gist, provided by someone on [this thread](https://github.com/docker-library/openjdk/issues/46#issuecomment-118231415), should work? https://gist.github.com/md5/7fb07efafee3802da457

**Comment by shrishrirang** [comment]
Currently, the docker image being used is an alpine image. We had moved to Ubuntu briefly, but we are again back to using an alpine image. However, the difference this time is that we are not using a headless jre anymore. 

I'll take a look at the repro instructions you shared. Thanks!

**Comment by shrishrirang** [comment]
https://github.com/Azure-App-Service/tomcat/pull/17/commits/9de23e21288066a18cd808ec22787757cdc9731e addresses the font issue. The updated Tomcat images are live now. If you see any issues, feel free to report them.
